version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/" 
    rebase-strategy: disabled 
    schedule:
      interval: "weekly"
    groups:
      id: dev
      dependency-type: development
      patterns: '*'
      
