version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/" 
    rebase-strategy: disabled 
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies:
        dependency-type: development
        patterns: 
          - '*'