name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  node-version: 20.x

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Linting
        run: npm run lint

      - name: Run tests Linux
        run: xvfb-run -a npm test
        if: runner.os == 'Linux'

      - name: Run tests non Linux
        run: npm test
        if: runner.os != 'Linux'

      - name: Publish Integration Test Results
        if: always() && github.actor != 'dependabot[bot]'
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: './junit-testresults.xml'
          check_name: Tests

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Package
        run: vsce package

      - name: Upload extension as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: '*.vsix'

